version: '2'

services:
    #  redis:
    #    image: redis:latest
    #    container_name: redis
    #    ports:
    #      - "6379:6379"
    postgres:
        container_name: blog_postgres_container1
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-root}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - postgres
        restart: unless-stopped
    #  mailhog:
    #    image: mailhog/mailhog:latest
    #    restart: always
    #    ports:
    #      - 1025:2525
    #      - 8025:8025

networks:
    postgres:
        driver: bridge

volumes:
    postgres:
